from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('state_machine', src, depend = ['PKG_STATE_MACHINE_USING_EXAMPLE'], CPPPATH = CPPPATH)

Return('group')
