from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('state_machine', src, depend = ['PKG_USING_STATE_MACHINE'], CPPPATH = CPPPATH)

Return('group')
