from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('agile_led', src, depend = ['PKG_USING_STATE_MACHINE'], CPPPATH = CPPPATH)

Return('group')
